server:
  http:
    addr: 0.0.0.0:8002
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:wang111000@tcp(127.0.0.1:3306)/machine?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  jwt_key: 77037723115d7687c63b258b3cb1d19b # md5 system3app